/**
 * Terms of Service page with ZEKE branding
 */

import { createMetadata } from "@zeke/seo/metadata";
import { Card, CardContent } from "@zeke/ui/card";
import type { Metadata } from "next";

export const metadata: Metadata = createMetadata({
	title: "Terms of Service - ZEKE",
	description:
		"Terms and conditions for using the ZEKE research intelligence platform.",
});

export default function TermsPage(): JSX.Element {
	return (
		<div className="w-full">
			<div className="container mx-auto">
				<div className="flex flex-col items-center gap-8 py-20">
					<div className="flex flex-col gap-4 text-center">
						<h1 className="max-w-4xl font-regular text-4xl tracking-tighter md:text-5xl">
							Terms of Service
						</h1>
						<p className="max-w-2xl text-lg text-muted-foreground leading-relaxed tracking-tight">
							The terms and conditions for using the ZEKE research intelligence
							platform
						</p>
					</div>
				</div>

				<div className="py-10">
					<div className="mx-auto max-w-4xl">
						<Card>
							<CardContent className="prose prose-gray dark:prose-invert max-w-none p-8">
								<h2>Agreement to Terms</h2>
								<p>
									By accessing or using ZEKE, operated by{" "}
									<strong>Minton Holdings LLC</strong>, you agree to be bound by
									these Terms of Service and our Privacy Policy.
								</p>

								<h3>Description of Service</h3>
								<p>
									ZEKE is a research intelligence platform that helps you
									compress research from 10 hours to 5 minutes by:
								</p>
								<ul>
									<li>Analyzing podcasts, papers, videos, and posts</li>
									<li>
										Generating verified briefs with citations and timestamps
									</li>
									<li>
										Creating role-aware takeaways and actionable playbooks
									</li>
									<li>
										Producing ready-to-use content with proper attribution
									</li>
								</ul>

								<h3>Acceptable Use</h3>
								<p>
									You may use ZEKE for legitimate research and business
									purposes. You agree not to:
								</p>
								<ul>
									<li>Submit content you do not have rights to analyze</li>
									<li>Use the service for illegal or harmful activities</li>
									<li>Attempt to reverse engineer or copy our algorithms</li>
									<li>Overload our systems or interfere with other users</li>
									<li>
										Republish generated content without proper attribution
									</li>
								</ul>

								<h3>Content and Intellectual Property</h3>
								<p>
									<strong>Your Content:</strong> You retain ownership of content
									you submit. You grant us a license to process and analyze it
									to provide our services.
								</p>
								<p>
									<strong>Generated Content:</strong> Briefs, insights, and
									playbooks generated by ZEKE are provided for your use, but you
									are responsible for verifying accuracy and respecting source
									copyrights.
								</p>
								<p>
									<strong>Our Platform:</strong> ZEKE's technology, algorithms,
									and interface are our intellectual property and protected by
									applicable laws.
								</p>

								<h3>Accuracy and Verification</h3>
								<p>
									While ZEKE provides citations and timestamps for verification,
									you are responsible for:
								</p>
								<ul>
									<li>Verifying the accuracy of generated insights</li>
									<li>
										Checking source material before making business decisions
									</li>
									<li>Understanding that AI analysis may contain errors</li>
									<li>
										Using your professional judgment when applying insights
									</li>
								</ul>

								<h3>Subscription and Billing</h3>
								<p>
									Paid subscriptions are billed in advance. You may cancel
									anytime, but refunds are provided only as required by law or
									at our discretion.
								</p>

								<h3>Privacy and Data</h3>
								<p>
									Your privacy is important to us. Please review our Privacy
									Policy to understand how we collect, use, and protect your
									data.
								</p>

								<h3>Limitation of Liability</h3>
								<p>
									ZEKE is provided "as is" without warranties. We are not liable
									for business decisions made based on generated insights or any
									indirect damages from using our service.
								</p>

								<h3>Termination</h3>
								<p>
									Either party may terminate this agreement. Upon termination,
									you lose access to the service but may export your data as
									described in our Privacy Policy.
								</p>

								<h3>Changes to Terms</h3>
								<p>
									We may update these terms occasionally. Significant changes
									will be communicated via email or platform notifications.
								</p>

								<h3>Contact</h3>
								<p>
									Questions about these terms? Contact us via our
									<a href="/contact" className="text-primary hover:underline">
										{" "}
										Support page
									</a>
									.
								</p>

								<p className="text-muted-foreground text-sm">
									<strong>Effective date:</strong> September 3, 2025
									<br />
									<strong>Last updated:</strong> September 3, 2025
									<br />
									<strong>Governing law:</strong> Delaware, United States
								</p>
							</CardContent>
						</Card>
					</div>
				</div>
			</div>
		</div>
	);
}
